services:
  - type: web
    name: openera-backend-api
    runtime: node
    plan: starter  # Change to paid plan for production
    region: oregon  # Change to your preferred region
    branch: main
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    healthCheckPath: /ping
    autoDeploy: false  # Set to true for automatic deployments
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: BCRYPT_ROUNDS
        value: 12
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: SUBMISSION_RATE_LIMIT_MAX
        value: 5
      - key: SUBMISSION_RATE_LIMIT_WINDOW_MS
        value: 3600000
      - key: LOG_LEVEL
        value: info
      - key: LOG_FILE
        value: logs/openera.log

databases:
  - name: openera-hackathon-db
    databaseName: openera_hackathon
    user: openera_user
    plan: free  # Change to paid plan for production
    region: oregon  # Same region as web service
    
# Note: The following environment variables need to be set manually in Render dashboard:
# - DATABASE_URL (auto-generated by Render PostgreSQL)
# - JWT_SECRET (generate a secure 32+ character string)
# - JWT_REFRESH_SECRET (generate a different secure 32+ character string)
# - ADMIN_EMAIL
# - ADMIN_PASSWORD
# - ADMIN_NAME
# - CORS_ORIGIN
